/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.110
 * Generated at: 2025-12-09 19:54:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava.editors;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.Collection;
import java.util.Map;
import org.openxava.util.Maps;
import org.openxava.util.Is;
import org.openxava.util.XavaPreferences;
import org.openxava.view.View;
import org.openxava.model.meta.MetaProperty;
import org.openxava.model.meta.MetaReference;
import org.openxava.model.meta.MetaEntity;
import org.openxava.model.meta.MetaCollection;
import org.openxava.web.WebEditors;
import org.openxava.controller.meta.MetaController;
import org.openxava.controller.meta.MetaAction;
import org.openxava.web.Ids;
import org.openxava.controller.meta.MetaControllers;
import org.openxava.util.Is;
import org.openxava.util.XavaPreferences;

public final class collectionEditor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/xava/collectionFromModel.jsp", Long.valueOf(1760748036000L));
    _jspx_dependants.put("jar:file:/C:/Users/zamm/Desktop/Proyecto_POO/Proyecto_ReservaNatural-POO-/Proyecto-Reserva-Natural-main/Proyecto-Reserva-Natural-main/target/proyectoReservaa/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt-1_0.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/xava/imports.jsp", Long.valueOf(1760748040000L));
    _jspx_dependants.put("/xava/collectionList.jsp", Long.valueOf(1760748036000L));
    _jspx_dependants.put("jar:file:/C:/Users/zamm/Desktop/Proyecto_POO/Proyecto_ReservaNatural-POO-/Proyecto-Reserva-Natural-main/Proyecto-Reserva-Natural-main/target/proyectoReservaa/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1762017936242L));
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1760748036000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(22);
    _jspx_imports_classes.add("org.openxava.model.meta.MetaProperty");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaController");
    _jspx_imports_classes.add("org.openxava.model.meta.MetaEntity");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.openxava.util.XavaPreferences");
    _jspx_imports_classes.add("org.openxava.model.meta.MetaReference");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("org.openxava.web.Ids");
    _jspx_imports_classes.add("org.openxava.util.Is");
    _jspx_imports_classes.add("org.openxava.model.meta.MetaCollection");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaAction");
    _jspx_imports_classes.add("org.openxava.util.Maps");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.openxava.view.View");
    _jspx_imports_classes.add("org.openxava.web.WebEditors");
    _jspx_imports_classes.add("org.openxava.controller.meta.MetaControllers");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005falwaysAvailable_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005falwaysAvailable_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005falwaysAvailable_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.openxava.controller.ModuleContext context = null;
      synchronized (session) {
        context = (org.openxava.controller.ModuleContext) _jspx_page_context.getAttribute("context", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (context == null){
          context = new org.openxava.controller.ModuleContext();
          _jspx_page_context.setAttribute("context", context, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      org.openxava.util.Messages errors = null;
      errors = (org.openxava.util.Messages) _jspx_page_context.getAttribute("errors", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (errors == null){
        errors = new org.openxava.util.Messages();
        _jspx_page_context.setAttribute("errors", errors, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.openxava.web.style.Style style = null;
      style = (org.openxava.web.style.Style) _jspx_page_context.getAttribute("style", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (style == null){
        style = new org.openxava.web.style.Style();
        _jspx_page_context.setAttribute("style", style, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String collectionName = request.getParameter("collectionName");
String viewObject = request.getParameter("viewObject");
String listEditor = request.getParameter("listEditor");  
View view = (View) context.get(request, viewObject);
View collectionView = view.getSubview(collectionName);
if (!Is.emptyString(listEditor)) {
	collectionView.setDefaultListActionsForCollectionsIncluded(false);
	collectionView.setDefaultRowActionsForCollectionsIncluded(false); 
}
View subview = view.getSubview(collectionName);
MetaReference ref = view.getMetaModel().getMetaCollection(collectionName).getMetaReference();
String viewName = viewObject + "_" + collectionName;
String propertyPrefixAccumulated = request.getParameter("propertyPrefix");
String idCollection = org.openxava.web.Collections.id(request, collectionName); 
boolean collectionEditable = subview.isCollectionEditable();
boolean collectionMembersEditables = subview.isCollectionMembersEditables();
boolean hasListActions = subview.hasListActions();
String lineAction = ""; 
if (collectionEditable || collectionMembersEditables) {
	lineAction = subview.getEditCollectionElementAction();
}
else {
	lineAction = subview.getViewCollectionElementAction();
}
String propertyPrefix = propertyPrefixAccumulated == null?collectionName + ".":propertyPrefixAccumulated + collectionName + "."; 

      out.write("\r\n");
      out.write("<table width=\"100%\" ");
      out.print(style.getListCellSpacing());
      out.write('>');
      out.write('\r');
      out.write('\n');

	// New
if (view.displayDetailInCollection(collectionName)) {
	context.put(request, viewName, collectionView);

      out.write("\r\n");
      out.write("<tr class=");
      out.print(style.getCollectionListActions());
      out.write("><td colspan=\"");
      out.print(subview.getMetaPropertiesList().size()+1);
      out.write("\" class=");
      out.print(style.getCollectionListActions());
      out.write('>');
      out.write('\r');
      out.write('\n');

	if (collectionEditable) {

      out.write('\r');
      out.write('\n');
 if (subview.isRepresentsEntityReference()) { 
      out.write('\r');
      out.write('\n');
      String _jspx_temp0_url = "../barButton.jsp";
      String _jspx_temp0_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp0_url + ((_jspx_temp0_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getAddCollectionElementAction()), _jspx_temp0_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), _jspx_temp0_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');
 } 
      out.write('\r');
      out.write('\n');
      String _jspx_temp1_url = "../barButton.jsp";
      String _jspx_temp1_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp1_url + ((_jspx_temp1_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getNewCollectionElementAction()), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), _jspx_temp1_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');
 if (subview.isRepresentsEntityCollection()) { 
      out.write('\r');
      out.write('\n');
      String _jspx_temp2_url = "../barButton.jsp";
      String _jspx_temp2_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp2_url + ((_jspx_temp2_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getRemoveSelectedCollectionElementsAction()), _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), _jspx_temp2_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');
 } 
      out.write('\r');
      out.write('\n');
      String _jspx_temp3_url = "../barButton.jsp";
      String _jspx_temp3_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp3_url + ((_jspx_temp3_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", _jspx_temp3_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(subview.getDeleteSelectedCollectionElementsAction()), _jspx_temp3_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp3_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), _jspx_temp3_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');

	}

      out.write('\r');
      out.write('\n');

	Iterator itListActions = subview.getActionsNamesList().iterator();
while (itListActions.hasNext()) {

      out.write('\r');
      out.write('\n');
      String _jspx_temp4_url = "../barButton.jsp";
      String _jspx_temp4_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp4_url + ((_jspx_temp4_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", _jspx_temp4_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(itListActions.next().toString()), _jspx_temp4_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp4_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), _jspx_temp4_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');

	} // while list actions
	
	Collection<String> listSubcontrollers = subview.getSubcontrollersNamesList();
	for(String listSubcontroller : listSubcontrollers){
		
      out.write("\r\n");
      out.write("		");
      String _jspx_temp5_url = "../subButton.jsp";
      String _jspx_temp5_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp5_url + ((_jspx_temp5_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("controller", _jspx_temp5_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(listSubcontroller), _jspx_temp5_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp5_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("viewObject="+viewName), _jspx_temp5_requestEncoding), out, false);
      out.write("\r\n");
      out.write("		");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");

	}
else {

      out.write("\r\n");
      out.write("<td></td>\r\n");

	String argv = "collectionName=" + collectionName;
	Iterator it = subview.getMetaPropertiesList().iterator();
	String app = request.getParameter("application");
	String module = request.getParameter("module");
	while (it.hasNext()) {
		MetaProperty p = (MetaProperty) it.next(); 
		String propertyKey= propertyPrefix + p.getName();
		String valueKey = propertyKey + ".value";
		request.setAttribute(propertyKey, p);
		request.setAttribute(valueKey, subview.getValue(p.getName()));
		Object value = request.getAttribute(propertyKey + ".value");
		if (WebEditors.mustToFormat(p, view.getViewName())) {
			String fvalue = WebEditors.format(request, p, value, errors, view.getViewName());
			request.setAttribute(propertyKey + ".fvalue", fvalue);
		}

      out.write("\r\n");
      out.write("	<td>\r\n");
      out.write("		");
      String _jspx_temp6_url = WebEditors.getUrl(p, view.getViewName());
      String _jspx_temp6_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp6_url + ((_jspx_temp6_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("propertyKey", _jspx_temp6_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(propertyKey), _jspx_temp6_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("editable", _jspx_temp6_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", _jspx_temp6_requestEncoding), out, false);
      out.write("		\r\n");
      out.write("	</td>\r\n");
      out.write("	");

		}
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td>\r\n");

	try {

      out.write('\r');
      out.write('\n');
      out.write('	');

		if (!Is.emptyString(listEditor)) {
	
      out.write(" 		\r\n");
      out.write("		");
      String _jspx_temp7_url = listEditor;
      String _jspx_temp7_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp7_url + ((_jspx_temp7_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rowAction", _jspx_temp7_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(lineAction), _jspx_temp7_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", _jspx_temp7_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), _jspx_temp7_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');

		} else if (collectionView.isCollectionFromModel()) {
	
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

org.openxava.util.Messages messages = (org.openxava.util.Messages) request.getAttribute("messages");
if (messages == null) {
    messages = new org.openxava.util.Messages();
    request.setAttribute("messages", messages);
}
org.openxava.controller.ModuleManager manager = (org.openxava.controller.ModuleManager) context.get(request, "manager", "org.openxava.controller.ModuleManager");
String tabObject = request.getParameter("tabObject"); 
tabObject = (tabObject == null || tabObject.equals(""))?"xava_tab":tabObject;
String onSelectCollectionElementAction = subview.getOnSelectCollectionElementAction();
MetaAction onSelectCollectionElementMetaAction = Is.empty(onSelectCollectionElementAction) ? null : MetaControllers.getMetaAction(onSelectCollectionElementAction);
boolean resizeColumns = style.allowsResizeColumns() && XavaPreferences.getInstance().isResizeColumns();
boolean sortable = subview.isCollectionSortable();

      out.write('\r');
      out.write('\n');
 if (resizeColumns) { 
      out.write(" \r\n");
      out.write("<div class=\"");
      if (_jspx_meth_xava_005fid_005f0(_jspx_page_context))
        return;
      out.write(" ox-overflow-auto\">\r\n");
 } 
      out.write("\r\n");
      out.write("<table id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f1 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      _jspx_th_xava_005fid_005f1.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f1.setParent(null);
      // /xava/collectionFromModel.jsp(26,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f1.setName(idCollection);
      int _jspx_eval_xava_005fid_005f1 = _jspx_th_xava_005fid_005f1.doStartTag();
      if (_jspx_th_xava_005fid_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f1);
      out.write("\" class=\"ox-list\" ");
      out.print(style.getListCellSpacing());
      out.write('>');
      out.write('\r');
      out.write('\n');
 if (sortable) { 
      out.write("<tbody class=\"xava_sortable_row\">");
 } 
      out.write(" \r\n");
      out.write("<tr class=\"ox-list-header\">\r\n");
      out.write("	");

		if (lineAction != null) {
	
      out.write("	\r\n");
      out.write("	<th class=\"ox-list-header\"></th>\r\n");
      out.write("	");

		}
	
      out.write("	\r\n");
      out.write("	<th class=\"ox-list-header\" width=\"5\">\r\n");
      out.write("	");

	
      out.write("\r\n");
      out.write("	<input type=\"checkbox\" name=\"");
      if (_jspx_meth_xava_005fid_005f2(_jspx_page_context))
        return;
      out.write("\" value=\"");
      out.print(propertyPrefix);
      out.write("selected_all\" \r\n");
      out.write("		data-on-select-collection-element-action=\"");
      out.print(onSelectCollectionElementAction);
      out.write("\"\r\n");
      out.write("		data-view-object=\"");
      out.print(idCollection);
      out.write("\"\r\n");
      out.write("		data-prefix=\"");
      out.print(propertyPrefix);
      out.write("\"\r\n");
      out.write("		data-tab-object=\"");
      out.print(tabObject);
      out.write("\"/>\r\n");
      out.write("	</th>\r\n");

	// Heading
boolean singleLineHeader = false; // By now a fixed value 	
Iterator it = subview.getMetaPropertiesList().iterator();
for (int columnIndex=0; it.hasNext(); columnIndex++) {
	MetaProperty p = (MetaProperty) it.next();
	String label = p.getQualifiedLabel(request);
	int columnWidth = subview.getCollectionColumnWidth(columnIndex);
	String width = columnWidth<0 || !resizeColumns?"":"data-width=" + columnWidth;
	String widthClass = width.equals("")?"ox-list-default-column-width":"";

      out.write("\r\n");
      out.write("	<th class=\"ox-list-header ox-padding-right-0\">\r\n");
      out.write("		<div id=\"");
      //  xava:id
      org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f3 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
      _jspx_th_xava_005fid_005f3.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fid_005f3.setParent(null);
      // /xava/collectionFromModel.jsp(57,11) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fid_005f3.setName(idCollection);
      int _jspx_eval_xava_005fid_005f3 = _jspx_th_xava_005fid_005f3.doStartTag();
      if (_jspx_th_xava_005fid_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f3);
      out.write("_col");
      out.print(columnIndex);
      out.write("\" class=\"");
      out.print(((resizeColumns)?("xava_resizable"):("")));
      out.write(' ');
      out.print(widthClass);
      out.write('"');
      out.write(' ');
      out.print(width);
      out.write(">\r\n");
      out.write("		");
if (singleLineHeader && resizeColumns) {
      out.write("<nobr>");
}
      out.write("\r\n");
      out.write("		");
      out.print(label);
      out.write("&nbsp;\r\n");
      out.write("		");
if (singleLineHeader && resizeColumns) {
      out.write("</nobr>");
}
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</th>\r\n");

	}

      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

	// Values
Collection aggregates = subview.getCollectionValues();
View parent = view.getParent();
boolean parentHasSections = parent != null && parent.hasSections();
boolean condition = (view.isKeyEditable() && parentHasSections && !view.isRepresentsEntityReference()); 
if (aggregates == null || condition) aggregates = java.util.Collections.EMPTY_LIST;
Iterator itAggregates = aggregates.iterator();
for (int f=0; itAggregates.hasNext(); f++) {
	Map row = (Map) itAggregates.next();
	String cssClass=f%2==0?"ox-list-pair":"ox-list-odd";
	String cssCellClass=f%2==0?"ox-list-pair":"ox-list-odd";
	String selectedClass = "";
	if (f == subview.getCollectionEditingRow()) { 
		selectedClass = f%2==0?style.getListPairSelected():style.getListOddSelected();
		cssClass = cssClass + " " + selectedClass;		
		if (style.isApplySelectedStyleToCellInList()) cssCellClass = cssCellClass + " " + selectedClass; 
	}		
	String idRow = Ids.decorate(request, propertyPrefix) + f;	
	String events=f%2==0?style.getListPairEvents():style.getListOddEvents(); 

      out.write("\r\n");
      out.write("<tr id=\"");
      out.print(idRow);
      out.write("\" class=\"");
      out.print(cssClass);
      out.write('"');
      out.write(' ');
      out.print(events);
      out.write('>');
      out.write('\r');
      out.write('\n');

	if (lineAction != null) {

      out.write("\r\n");
      out.write("<td class=\"");
      out.print(cssCellClass);
      out.write(" ox-list-action-cell\">\r\n");
      out.write("<nobr>\r\n");
      out.write("	");
	if (sortable) { 
      out.write("\r\n");
      out.write("	<i class=\"xava_handle mdi mdi-swap-vertical\"></i>	\r\n");
      out.write("	");
  } 
      out.write('	');
      out.write('\r');
      out.write('\n');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f0 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      _jspx_th_xava_005faction_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005faction_005f0.setParent(null);
      // /xava/collectionFromModel.jsp(98,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005faction_005f0.setAction(lineAction);
      // /xava/collectionFromModel.jsp(98,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005faction_005f0.setArgv("row="+f + ",viewObject="+viewName);
      int _jspx_eval_xava_005faction_005f0 = _jspx_th_xava_005faction_005f0.doStartTag();
      if (_jspx_th_xava_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f0);
      out.write('\r');
      out.write('\n');
 		
		if (style.isSeveralActionsPerRow()) {
			String argv = "row=" + f + ",viewObject="+viewName;
			Collection<String> rowActionNames = view.removeUnavailableActionFromRow(subview.getRowActionsNames(), argv);
			boolean hasIconOrImage = view.isRowActionHaveIcon(rowActionNames);
			if (rowActionNames.size() < XavaPreferences.getInstance().getRowActionsPopupThreshold() - 1) { 
				for (java.util.Iterator itRowActions = rowActionNames.iterator(); itRowActions.hasNext(); ) { 	
					String rowAction = (String) itRowActions.next();		

      out.write('\r');
      out.write('\n');
      //  xava:action
      org.openxava.web.taglib.ActionTag _jspx_th_xava_005faction_005f1 = (org.openxava.web.taglib.ActionTag) _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005falwaysAvailable_005faction_005fnobody.get(org.openxava.web.taglib.ActionTag.class);
      _jspx_th_xava_005faction_005f1.setPageContext(_jspx_page_context);
      _jspx_th_xava_005faction_005f1.setParent(null);
      // /xava/collectionFromModel.jsp(108,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005faction_005f1.setAction(rowAction);
      // /xava/collectionFromModel.jsp(108,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005faction_005f1.setArgv(argv);
      // /xava/collectionFromModel.jsp(108,0) name = alwaysAvailable type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005faction_005f1.setAlwaysAvailable(true);
      int _jspx_eval_xava_005faction_005f1 = _jspx_th_xava_005faction_005f1.doStartTag();
      if (_jspx_th_xava_005faction_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fxava_005faction_0026_005fargv_005falwaysAvailable_005faction_005fnobody.reuse(_jspx_th_xava_005faction_005f1);
      out.write('\r');
      out.write('\n');

				}
			} else {

      out.write("\r\n");
      out.write("<a class=\"ox-image-link xava_popup_menu_icon\">\r\n");
      out.write("	<i class=\"mdi mdi-dots-vertical\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"ox-popup-menu ox-image-link ox-display-none\">\r\n");
		
				for (java.util.Iterator itRowActions = rowActionNames.iterator(); itRowActions.hasNext(); ) { 	
					String rowActionString = (String) itRowActions.next();			

      out.write("\r\n");
      out.write("	<li>\r\n");
      out.write("		");
      String _jspx_temp8_url = "../barButton.jsp";
      String _jspx_temp8_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp8_url + ((_jspx_temp8_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("action", _jspx_temp8_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(rowActionString), _jspx_temp8_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("addSpaceWithoutImage", _jspx_temp8_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(hasIconOrImage), _jspx_temp8_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("argv", _jspx_temp8_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf("row=" + f + ",viewObject="+viewName), _jspx_temp8_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("alwaysAvailable", _jspx_temp8_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", _jspx_temp8_requestEncoding), out, false);
      out.write("\r\n");
      out.write("	</li>\r\n");

				}

      out.write("\r\n");
      out.write("</ul>\r\n");

			}
		} 

      out.write("\r\n");
      out.write("</nobr>\r\n");
      out.write("</td>\r\n");

	}

      out.write("\r\n");
      out.write("<td class=\"");
      out.print(cssCellClass);
      out.write("\" width=\"5\">\r\n");
      out.write("<input class=\"xava_selected\" type=\"checkbox\" name=\"");
      if (_jspx_meth_xava_005fid_005f4(_jspx_page_context))
        return;
      out.write("\" value=\"");
      out.print(propertyPrefix);
      out.write("__SELECTED__:");
      out.print(f);
      out.write("\" \r\n");
      out.write("	data-on-select-collection-element-action=\"");
      out.print(onSelectCollectionElementAction);
      out.write("\"\r\n");
      out.write("	data-row-id=\"");
      out.print(idRow);
      out.write("\"\r\n");
      out.write("	data-row=\"");
      out.print(f);
      out.write("\"\r\n");
      out.write("	data-view-object=\"");
      out.print(viewName);
      out.write("\"\r\n");
      out.write("	data-tab-object=\"");
      out.print(tabObject);
      out.write("\"\r\n");
      out.write("	data-confirm-message=\"");
      out.print(Is.empty(onSelectCollectionElementMetaAction)?"":onSelectCollectionElementMetaAction.getConfirmMessage());
      out.write("\"\r\n");
      out.write("	data-takes-long=\"");
      out.print(Is.empty(onSelectCollectionElementMetaAction)?false:onSelectCollectionElementMetaAction.isTakesLong());
      out.write("\"\r\n");
      out.write("/>\r\n");
      out.write("</td>\r\n");

	it = subview.getMetaPropertiesList().iterator();	
	for (int columnIndex = 0; it.hasNext(); columnIndex++) { 
		MetaProperty p = (MetaProperty) it.next();
		String align =p.isNumber() && !p.hasValidValues()?"ox-text-align-right":"";
		int columnWidth = subview.getCollectionColumnWidth(columnIndex);
		String width = columnWidth<0 || !resizeColumns?"":"data-width=" + columnWidth;
		String widthClass = width.equals("")?"ox-list-default-column-width":""; 
		String fvalue = null;
		Object value = null;
		String propertyName = p.getName();
		value = Maps.getValueFromQualifiedName(row, propertyName);
		fvalue = WebEditors.format(request, p, value, errors, view.getViewName(), true);	
		Object title = WebEditors.formatTitle(request, p, value, errors, view.getViewName(), true); 

      out.write("\r\n");
      out.write("	<td class=\"");
      out.print(cssCellClass);
      out.write(' ');
      out.print(align);
      out.write(" ox-list-data-cell\">\r\n");
      out.write("	");
      //  xava:link
      org.openxava.web.taglib.LinkTag _jspx_th_xava_005flink_005f0 = (org.openxava.web.taglib.LinkTag) _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.get(org.openxava.web.taglib.LinkTag.class);
      _jspx_th_xava_005flink_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005flink_005f0.setParent(null);
      // /xava/collectionFromModel.jsp(170,1) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005flink_005f0.setAction(lineAction);
      // /xava/collectionFromModel.jsp(170,1) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005flink_005f0.setArgv("row="+f + ",viewObject="+viewName);
      int _jspx_eval_xava_005flink_005f0 = _jspx_th_xava_005flink_005f0.doStartTag();
      if (_jspx_eval_xava_005flink_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<div title=\"");
          out.print(title);
          out.write("\" class=\"");
          if (_jspx_meth_xava_005fid_005f5(_jspx_th_xava_005flink_005f0, _jspx_page_context))
            return;
          out.write(' ');
          //  xava:id
          org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f6 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
          _jspx_th_xava_005fid_005f6.setPageContext(_jspx_page_context);
          _jspx_th_xava_005fid_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_xava_005flink_005f0);
          // /xava/collectionFromModel.jsp(171,58) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_xava_005fid_005f6.setName(idCollection);
          int _jspx_eval_xava_005fid_005f6 = _jspx_th_xava_005fid_005f6.doStartTag();
          if (_jspx_th_xava_005fid_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
          _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f6);
          out.write("_col");
          out.print(columnIndex);
          out.write(' ');
          out.print(widthClass);
          out.write('"');
          out.write(' ');
          out.print(width);
          out.write(">\r\n");
          out.write("	");
if (resizeColumns) {
          out.write("<nobr>");
}
          out.write('\r');
          out.write('\n');
          out.write('	');
          out.print(fvalue);
          out.write("&nbsp; \r\n");
          out.write("	");
if (resizeColumns) {
          out.write("</nobr>");
}
          out.write("\r\n");
          out.write("	</div>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_xava_005flink_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_xava_005flink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fxava_005flink_0026_005fargv_005faction.reuse(_jspx_th_xava_005flink_005f0);
      out.write("\r\n");
      out.write("	</td>\r\n");
      out.write("		\r\n");

	}
}

      out.write("\r\n");
      out.write("</tr>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "collectionTotals.jsp", out, false);
      out.write('\r');
      out.write('\n');
 if (sortable) { 
      out.write("</tbody>");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
 if (resizeColumns) { 
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.write('	');
 } else { 
      out.write("\r\n");
      out.write("		");

String tabObject = org.openxava.web.Collections.tabObject(idCollection); 
org.openxava.tab.Tab tab = subview.getCollectionTab();

String tabPrefix = tabObject + "_";
tab.clearStyle();
int selectedRow = subview.getCollectionEditingRow();
if (selectedRow >= 0) {
	String cssClass=selectedRow%2==0?style.getListPairSelected():style.getListOddSelected();
	tab.setStyle(selectedRow, cssClass);
}
context.put(request, tabObject, tab);

// The list

      out.write('\r');
      out.write('\n');
      String _jspx_temp9_url = "../list.jsp";
      String _jspx_temp9_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp9_url + ((_jspx_temp9_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("collection", _jspx_temp9_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(idCollection), _jspx_temp9_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("rowAction", _jspx_temp9_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(lineAction), _jspx_temp9_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabObject", _jspx_temp9_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(tabObject), _jspx_temp9_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", _jspx_temp9_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), _jspx_temp9_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewKeyEditable", _jspx_temp9_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(view.isKeyEditable()), _jspx_temp9_requestEncoding), out, false);
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('	');
 } 
      out.write('\r');
      out.write('\n');
 } catch (Exception ex) { 
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td class='ox-errors'>\r\n");
      out.print(ex.getLocalizedMessage());
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_xava_005fid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f0 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    _jspx_th_xava_005fid_005f0.setPageContext(_jspx_page_context);
    _jspx_th_xava_005fid_005f0.setParent(null);
    // /xava/collectionFromModel.jsp(24,12) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_xava_005fid_005f0.setName("collection_scroll");
    int _jspx_eval_xava_005fid_005f0 = _jspx_th_xava_005fid_005f0.doStartTag();
    if (_jspx_th_xava_005fid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f0);
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f2 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    _jspx_th_xava_005fid_005f2.setPageContext(_jspx_page_context);
    _jspx_th_xava_005fid_005f2.setParent(null);
    // /xava/collectionFromModel.jsp(39,30) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_xava_005fid_005f2.setName("xava_selected_all");
    int _jspx_eval_xava_005fid_005f2 = _jspx_th_xava_005fid_005f2.doStartTag();
    if (_jspx_th_xava_005fid_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f2);
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f4 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    _jspx_th_xava_005fid_005f4.setPageContext(_jspx_page_context);
    _jspx_th_xava_005fid_005f4.setParent(null);
    // /xava/collectionFromModel.jsp(144,51) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_xava_005fid_005f4.setName("xava_selected");
    int _jspx_eval_xava_005fid_005f4 = _jspx_th_xava_005fid_005f4.doStartTag();
    if (_jspx_th_xava_005fid_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f4);
    return false;
  }

  private boolean _jspx_meth_xava_005fid_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_xava_005flink_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  xava:id
    org.openxava.web.taglib.IdTag _jspx_th_xava_005fid_005f5 = (org.openxava.web.taglib.IdTag) _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.get(org.openxava.web.taglib.IdTag.class);
    _jspx_th_xava_005fid_005f5.setPageContext(_jspx_page_context);
    _jspx_th_xava_005fid_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_xava_005flink_005f0);
    // /xava/collectionFromModel.jsp(171,32) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_xava_005fid_005f5.setName("tipable");
    int _jspx_eval_xava_005fid_005f5 = _jspx_th_xava_005fid_005f5.doStartTag();
    if (_jspx_th_xava_005fid_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fxava_005fid_0026_005fname_005fnobody.reuse(_jspx_th_xava_005fid_005f5);
    return false;
  }
}
